project_id = "your-supabase-project-id"

[functions.check-admin-status]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.populate-movies]
verify_jwt = false